### PR TITLE
Remove binding to UDP

### PR DESCRIPTION
**Pull request by business-goose**
this literally messes EVERYTHING up

### CODE REVIEW

**Comment by Phyremaster** [comment]
What messes everything up? Do you mean the UDP port being exposed? What is "everything" in this context? That UDP port is exposed because it is the default port for the standalone query protocol (yes, you can get the server list data from a request to the TCP port, but I'm sure many third-parties use the query protocol). If you personally really don't want that exposed for some reason, just don't forward UDP for the port.

**Comment by business-goose** [comment]
> What messes everything up? Do you mean the UDP port being exposed? What is "everything" in this context? That UDP port is exposed because it is the default port for the standalone query protocol (yes, you can get the server list data from a request to the TCP port, but I'm sure many third-parties use the query protocol). If you personally really don't want that exposed for some reason, just don't forward UDP for the port.

"Everything" in this context is like, you know, connecting to the server which 99% of people who play Minecraft multiplayer want to do? 
enable-query is disabled by default in server.properties. My issue here is that when I pull the Docker image (with Kitematic), it makes connecting to the server **impossible**, even with enabling query in server.properties.
image
Maybe it's an incompatibility issue with Kitematic? If so, do you mind mentioning how to fix this issue in the documentation?

**Comment by Phyremaster** [comment]
You don't appear to have the TCP port forwarded...

**Comment by business-goose** [comment]
> You don't appear to have the TCP port configured...

As is default, when using Kitematic...

**Comment by Phyremaster** [comment]
...So just configure it? Or if you _really_ want it to be set up by default, get Kitematic to fix their default port configuration feature.

**Pull request closed without merging**
